#12 POs should create issues
dwyl/product-owner-guide pull request #28
Opened 2018-01-16 15:09 UTC by Cleop

#12 Adds answer to why POs should create issues

2018-01-16 18:26 UTC, nelsonic approved these changes
👍

2018-01-17 16:04 UTC, iteles requested changes
Just a thought, won't require big changes.

2018-01-17 16:04 UTC, iteles commented on readme.md
> +
The points in this section make sense but I'm feeling that it's a change in 'voice'. Whereas most of this repo is written as if speaking to POs, these bullet points feel like they're written _about_ POs but _not_ as if they were the ones reading this.

2018-01-17 16:04 UTC, iteles commented on readme.md
> +- They learn from being asked the same questions a few times by developers and improve their creation of issues over time
This is a good example of what I mean, could come off as a little insulting...

2018-01-17 16:59 UTC, Cleop commented
@iteles - want to take a look at the new wording whenever you get a chance?

2018-01-18 11:52 UTC, iteles approved these changes
Thanks @Cleop 👍

2018-01-18 11:52 UTC, merged